[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
ast = true
build_info = true
extra_output = ["storageLayout"]
gas_reports = ["GamblingProtocol"]
evm_version = "cancun"
solc = "0.8.26"
fs_permissions = [{ access = "read", path = "./out" }]
viaIR = true
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
sepolia = "https://alpha-fittest-energy.ethereum-sepolia.quiknode.pro/ad2fa26d4fdae56c65fded4c4b8eadc7bd06778b/"
mainnet = "https://greatest-icy-rain.quiknode.pro/39f79e4968518a7d0519a3638f730848fc4663c2/"
base = "https://sly-damp-road.base-mainnet.quiknode.pro/7be795a85e70d1d223b6576b7b589970ab612649/"

[etherscan]
mainnet = { key = "1XAWBCQYA7MDDYWPE6DE6VB14JY2GE2FF6", url = "https://api.etherscan.io/api" }
base = { key = "FP42HAQ9ECZGGQUR27EWFDU44WPJ8273MF", url = "https://api.basescan.org/api" }
